/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardDirectorRouteImport } from './routes/dashboard/director'
import { Route as DashboardDocenteRouteImport } from './routes/dashboard/docente'
import { Route as DashboardEstudianteRouteImport } from './routes/dashboard/estudiante'
import { Route as DashboardGeneralRouteImport } from './routes/dashboard/general'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDirectorRoute = DashboardDirectorRouteImport.update({
  id: '/dashboard/director',
  path: '/dashboard/director',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocenteRoute = DashboardDocenteRouteImport.update({
  id: '/dashboard/docente',
  path: '/dashboard/docente',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEstudianteRoute = DashboardEstudianteRouteImport.update({
  id: '/dashboard/estudiante',
  path: '/dashboard/estudiante',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGeneralRoute = DashboardGeneralRouteImport.update({
  id: '/dashboard/general',
  path: '/dashboard/general',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/director': typeof DashboardDirectorRoute
  '/dashboard/docente': typeof DashboardDocenteRoute
  '/dashboard/estudiante': typeof DashboardEstudianteRoute
  '/dashboard/general': typeof DashboardGeneralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/director': typeof DashboardDirectorRoute
  '/dashboard/docente': typeof DashboardDocenteRoute
  '/dashboard/estudiante': typeof DashboardEstudianteRoute
  '/dashboard/general': typeof DashboardGeneralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/director': typeof DashboardDirectorRoute
  '/dashboard/docente': typeof DashboardDocenteRoute
  '/dashboard/estudiante': typeof DashboardEstudianteRoute
  '/dashboard/general': typeof DashboardGeneralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/director'
    | '/dashboard/docente'
    | '/dashboard/estudiante'
    | '/dashboard/general'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/director'
    | '/dashboard/docente'
    | '/dashboard/estudiante'
    | '/dashboard/general'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/director'
    | '/dashboard/docente'
    | '/dashboard/estudiante'
    | '/dashboard/general'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDirectorRoute: typeof DashboardDirectorRoute
  DashboardDocenteRoute: typeof DashboardDocenteRoute
  DashboardEstudianteRoute: typeof DashboardEstudianteRoute
  DashboardGeneralRoute: typeof DashboardGeneralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/director': {
      id: '/dashboard/director'
      path: '/dashboard/director'
      fullPath: '/dashboard/director'
      preLoaderRoute: typeof DashboardDirectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/docente': {
      id: '/dashboard/docente'
      path: '/dashboard/docente'
      fullPath: '/dashboard/docente'
      preLoaderRoute: typeof DashboardDocenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/estudiante': {
      id: '/dashboard/estudiante'
      path: '/dashboard/estudiante'
      fullPath: '/dashboard/estudiante'
      preLoaderRoute: typeof DashboardEstudianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/general': {
      id: '/dashboard/general'
      path: '/dashboard/general'
      fullPath: '/dashboard/general'
      preLoaderRoute: typeof DashboardGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDirectorRoute: DashboardDirectorRoute,
  DashboardDocenteRoute: DashboardDocenteRoute,
  DashboardEstudianteRoute: DashboardEstudianteRoute,
  DashboardGeneralRoute: DashboardGeneralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
